spring:
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/http_test?characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
    username: root

server:
  port: 8082
mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.h2t.study.po
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
